FROM node:16.15.0-alpine as build-env

COPY . ./app
WORKDIR /app

RUN npm run build:protoc
RUN npm run build

RUN GRPC_HEALTH_PROBE_VERSION=v0.3.1 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

CMD ["node", "dist/main.js"]